version: '3.4'

services:
  db:
    image: mysql:9.1.0
    #command: mysqld --default_authentication_plugin=mysql_native_password
    restart: on-failure
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: rest_with_spring_boot_kenjix
    ports:
      - "3308:3306"
    expose:
      - 3306
    networks:
      - kenjix-network
  spring_boot:
    image: gabrielleite03/spring_boot
    restart: on-failure
    build: ../../../../spring_boot
    working_dir: /spring_boot
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/rest_with_spring_boot_kenjix?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - kenjix-network
networks:
  kenjix-network:
      driver: bridge
