spring:
  application:
    name: rest-with-spring-boot-and-java-kenjix
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://KOTO-SERVER01:3306/rest_with_spring_boot_kenjix?useTimezone=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: true
    open-in-view: false
