name: RELEASE | CI/CD with GitHub Actions

on:
  push:
    branches:
      - release

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # precisa para poder criar tags
      - name: setup jdk 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Packaging the Application
        run: mvn clean package
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Docker Compose Building
        working-directory: ./recursos/docker/docker-compose
        run: docker compose build
      - name: Printing image name and version
        run: echo "::notice::${{ secrets.DOCKER_USERNAME }}/spring_boot:rc-${{ github.run_number }}"
      - name: Push to Docker Container Registry
        run: |
            docker push ${{ secrets.DOCKER_USERNAME }}/spring_boot:latest
            docker tag ${{ secrets.DOCKER_USERNAME }}/spring_boot:latest ${{ secrets.DOCKER_USERNAME }}/spring_boot:rc-${{ github.run_number }}            
            docker push ${{ secrets.DOCKER_USERNAME }}/spring_boot:rc-${{ github.run_number }}