name: Continuos integrations and Delivery with GitHub Actions

on:
  push:
    branches:
      - develop

jobs:
  build-deploy:
    name: build and deploy spring_boot
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup jdk 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Packaging the Application
        run: mvn -B test --file pom.xml