name: Continuos integrations and Delivery with GitHub Actions

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu:latest

    steps:
      - uses: docker/login-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
          cache: maven