name: Continuos integrations and Delivery with GitHub Actions

on:
  push:
    branches:
      - "main"

jobs:
  build-deploy:
    name: build and deploy spring-api
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup jdk 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin' # See 'Supported distributions' for available options
          cache: maven
      - name: unit tests
        run: mvn -B test --file pom.xml
      - name: build the app
        run: |
            mvn clean
            mvn -B package --file pom.xml
      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/spring_boot:latest
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: push the docker image to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/spring_boot:latest